# Sniperkit-Bot
# - Status: analyzed

apiVersion: v1
kind: Service
metadata:
  name: mashling
  labels:
    app: mashling
spec:
  ports:
  - name: http
    port: 9096
  selector:
    app: mashling
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mashling
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mashling
    spec:
      containers:
      - name: mashling
        image: docker.io/<YOUR DOCKER USER>/mashling
        ports:
        - containerPort: 9096
#      imagePullSecrets:
#      - name: regsecret
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mashling-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mashling
spec:
  hosts:
  - "*"
  gateways:
  - mashling-gateway
  http:
  - match:
    - uri:
        prefix: /pets/
    route:
    - destination:
        host: mashling
        port:
          number: 9096
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: petstore
spec:
  hosts:
  - petstore.swagger.io
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
